apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: third-node-pod
      tier: backend
  template:
    metadata:
      labels:
        app: third-node-pod
        tier: backend
    spec:
      containers:
        - name: third-node-container
          image: jorge107/node-third-stories:v2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: third-node-configmap
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: third-node-volume
      volumes:
        - name: third-node-volume
          persistentVolumeClaim:
            claimName: third-node-volume-claim

          # emptyDir: {}




