apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: third-node-volume-claim
spec:
  volumeName: third-node-volume-persistent
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
